version: "3"
services:
  web:
    build: ./front
    stdin_open: true
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - mern-app

  api:
    build: ./back
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
